apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hotel-booking-cancellation-prediction-api-pdb
  namespace: hotel-booking-cancellation-prediction
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hotel-booking-cancellation-prediction-api
