{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hotel-booking-cancellation-prediction.fullname" . }}-pdb
  namespace: {{ include "hotel-booking-cancellation-prediction.namespace" . }}
  labels:
    {{- include "hotel-booking-cancellation-prediction.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "hotel-booking-cancellation-prediction.selectorLabels" . | nindent 6 }}
{{- end }}
